name: 'React Docker S2I'
description: 'Builds and pushes React app to GHCR'
inputs:
  registry:
    required: true
  username:
    required: true
  password:
    required: true
  image-name:
    required: true
  tag:
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: ./entrypoint.sh
