name: 'React Docker Build and Push'
description: 'Builds React app and pushes image to GHCR'
inputs:
  registry:
    required: true
  username:
    required: true
  password:
    required: true
  image-name:
    required: true
  tag:
    default: 'latest'
runs:
  using: 'docker'
  image: 'Dockerfile.react'
  args:
    - ./entrypoint.sh
